# Generated by Django 4.2.11 on 2024-09-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("pl", "Plants"),
                            ("al", "Animals"),
                            ("na", "Nature"),
                            ("pc", "Place"),
                        ],
                        max_length=80,
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("heading", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
